#!/bin/bash
. /var/openpanel/api/sh/module.sh

Awstats.update() {
  awstats=$(coreval Awstats awstatspass)
  authd runscript openapp-call "awstats" passwd "${awstats}"
}

A2CONFDIR=/etc/apache2/sites-enabled
ALIASCONFDIR=/etc/apache2/drupal-aliases
SSLDIR=/etc/ssl/private

restart_apache2() {

cat <<EOB > $(pwd)/ssl-namevirtualhost.conf
NameVirtualHost *:443
EOB

    [ ! -f /etc/apache2/conf.d/ssl-namevirtualhost.conf ] && authd installfile ssl-namevirtualhost.conf /etc/apache2/conf.d

    authd reloadservice apache2
}

Site.delete() {
    SITE_DOMAIN=$(coreval Site id)

    authd runscript openapp-drupal-sitealias removesite ${SITE_DOMAIN}
    authd runscript openapp-drupal-deletesite "${SITE_DOMAIN}" || exiterror "Error while removing site"

    authd deletefile ${A2CONFDIR}/${SITE_DOMAIN}.conf
    [ -r ${A2CONFDIR}/${SITE_DOMAIN}-ssl.conf ] && HTTPS.delete

    restart_apache2
}

Site.update() {
    SITE_DOMAIN=$(coreval Site id)
    SITE_NAME=$(coreval Site sitename)
    PASSWORD=$(coreval Site adminpass)
    SITE_ADMIN=$(coreval Site admin)
    ALIASES=$(coreval Site aliases | tr '\n' ' ')

    [ -z ${ALIASES} ] && ALIASES=${SITE_DOMAIN}
    [ -z ${SITE_ADMIN} ] && SITE_ADMIN=webmaster@unknown

    authd runscript openapp-drupal-sitealias removesite ${SITE_DOMAIN}
    authd runscript openapp-drupal-site-adminsettings "${SITE_DOMAIN}" "${PASSWORD}" "${SITE_ADMIN}" "${SITE_NAME}"

    for ALIAS in ${ALIASES}; do
        authd runscript openapp-drupal-sitealias addalias ${SITE_DOMAIN} ${ALIAS}
    done

cat <<EOB > $(pwd)/${SITE_DOMAIN}-aliases.conf
    ServerAlias ${ALIASES}
EOB

cat <<EOB > $(pwd)/${SITE_DOMAIN}.conf
<VirtualHost *:80>
    ServerAdmin ${SITE_ADMIN}
    Servername ${SITE_DOMAIN}
    Include ${ALIASCONFDIR}/${SITE_DOMAIN}-aliases.conf

    DocumentRoot /var/www

    CustomLog /var/log/apache2/${SITE_DOMAIN}.access.log combined
    ErrorLog  /var/log/apache2/${SITE_DOMAIN}.error.log
</VirtualHost>
EOB

    authd installfile ${SITE_DOMAIN}.conf ${A2CONFDIR}
    authd installfile ${SITE_DOMAIN}-aliases.conf ${ALIASCONFDIR}

    restart_apache2
}

Site.create() {
    SITE_DOMAIN=$(coreval Site id)
    SITE_NAME=$(coreval Site sitename)
    PASSWORD=$(coreval Site adminpass)
    SITE_ADMIN=$(coreval Site admin)

    authd runscript openapp-drupal-site-install "${SITE_DOMAIN}" "${SITE_NAME}" "${PASSWORD}" "${SITE_ADMIN}"

    Site.update
}

HTTPS.delete() {
    SERVERNAME=$(coreval Site id)

    authd deletefile ${A2CONFDIR}/${SERVERNAME}-ssl.conf
    authd deletedir ${SSLDIR}/${SERVERNAME}.pem

    restart_apache2
}

HTTPS.create() {
    SSLCERT=$(coreval HTTPS pem)
    SERVERNAME=$(coreval Site id)
    WEBMASTER=$(coreval Site admin)

    SSLIP="*"

cat <<EOB > $(pwd)/${SERVERNAME}.pem
${SSLCERT}
EOB

    /var/openpanel/bin/validatepem.py $(pwd)/${SERVERNAME}.pem

    [ $? -eq 0 ] || exiterror "Your certificate has issues. Is the private key included (and without a passphrase)?"

cat <<EOB > $(pwd)/${SERVERNAME}-ssl.conf
<VirtualHost ${SSLIP}:443>
    ServerAdmin ${WEBMASTER}
    Servername ${SERVERNAME}
    Include ${ALIASCONFDIR}/${SERVERNAME}-aliases.conf

    DocumentRoot /var/www/

    SSLEngine on
    SSLProtocol -all +TLSv1 +SSLv3
    SSLCertificateFile ${SSLDIR}/${SERVERNAME}.pem

    CustomLog /var/log/apache2/${SERVERNAME}.access.log combined
    ErrorLog  /var/log/apache2/${SERVERNAME}.error.log
</VirtualHost>
EOB

    authd installfile ${SERVERNAME}.pem ${SSLDIR}
    authd installfile ${SERVERNAME}-ssl.conf ${A2CONFDIR}

    restart_apache2
}

HTTPS.update() {
    HTTPS.create
}

Module.getconfig() {
  cat << _EOF_
  <openpanel.module>
    <dict id="Awstats" type="class">
      <dict id="Awstats">
            <string id="awstatspass">*</string>
      </dict>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppDrupal.module
