#!/bin/bash
. /var/openpanel/api/sh/module.sh

Vhost.delete() {
	SITE_DOMAIN=$(coreval Vhost id)

    authd runscript openapp-drupal-deletesite "${SITE_DOMAIN}"
}

Vhost.create() {
	SITE_DOMAIN=$(coreval Vhost id)
    SITE_NAME=$(coreval Vhost sitename)
    PASSWORD=$(coreval Vhost adminpass)
    SITE_ADMIN=$(coreval Vhost admin)

    authd runscript openapp-drupal-site-install "${SITE_DOMAIN}" "${SITE_NAME}" "${PASSWORD}" "${SITE_ADMIN}"
}

implement OpenAppDrupal.module
